steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/login-repo/login-api:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/login-repo/login-api:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - login-api
      - --image=europe-west1-docker.pkg.dev/$PROJECT_ID/login-repo/login-api:latest
      - --region=europe-west1
      - --platform=managed
      - --update-env-vars=TEST_USERNAME=testuser,TEST_PASSWORD=testpassword
