steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'model-serving'
    args:
      - 'build'
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/model-serving-repo/model-serving:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/model-serving-repo/model-serving:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'model-serving'
      - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/model-serving-repo/model-serving:$COMMIT_SHA'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'

substitutions:
  _REGION: europe-west1

options:
  logging: CLOUD_LOGGING_ONLY