steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/rag-repo/rag-api:$COMMIT_SHA'
      - '.'
    dir: 'RAG_api'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/rag-repo/rag-api:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rag-api'
      - '--image=europe-west1-docker.pkg.dev/$PROJECT_ID/rag-repo/rag-api:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'

options:
  logging: CLOUD_LOGGING_ONLY
